import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Map from "@/components/Map/";
import {fetch} from "next/dist/compiled/@edge-runtime/primitives/fetch";

export default function Home({age}) {
  console.log(age)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Map/>
      </main>
    </>
  )
}

export async function getStaticProps({params}){
  const req = await fetch('http://localhost:3000/api/age')
  const data = await req.json();

  return{
    props:{age: data},
  }
}